### ISSUE TITLE
willmage.com down?

### ISSUE THREAD

**Issue by Electromaster232** [willmage/backend#3]
Hey will I noticed you deleted the twitter for willmage and the website is down? What happened, I was working on an uploader for it too...

**Comment by propelling** [comment]
I think it died. Their discord server also got deleted (see image).
![image](https://user-images.githubusercontent.com/49493689/86541240-39938e00-bf03-11ea-9f6c-48643b709073.png)

**Comment by Electromaster232** [comment]
rip
